import scala.scalanative.benchmarks.target.scala-2.11.src_managed.main.benchmarks._
import scala.scalanative.benchmarks.benchmarks._
import scala.scalanative.benchmarks.bounce._
import scala.scalanative.benchmarks.cd._
import scala.scalanative.benchmarks.deltablue._
import scala.scalanative.benchmarks.havlak._
import scala.scalanative.benchmarks.json._
import scala.scalanative.benchmarks.list._
import scala.scalanative.benchmarks.mandelbrot._
import scala.scalanative.benchmarks.nbody._
import scala.scalanative.benchmarks.permute._
import scala.scalanative.benchmarks.queens._
import scala.scalanative.benchmarks.richards._
import scala.scalanative.benchmarks.sha512._
import scala.scalanative.benchmarks.sieve._
import scala.scalanative.benchmarks.som._
import scala.scalanative.benchmarks.storage._
import scala.scalanative.benchmarks.sudoku._
import scala.scalanative.benchmarks.towers._
import scala.scalanative.benchmarks.tracer._
import scala.scalanative.benchmarks.target.scala-2.11.src_managed.main.benchmarks._
